### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Kurouoe** [JingShing/dark_and_darker_bard#1]
How can i use this? im newbie

**Comment by JingShing** [comment]
I am still working on it. It seems that this script sometimes failed on dark and darker.

**Comment by Kurouoe** [comment]
> I am still working it. It seems that this script sometimes failed on dark and darker.

that sounds great, you comment when the project is finished, it looks very cool.

**Comment by JingShing** [comment]
I finally made a worked version. You can get it [in here](https://github.com/JingShing-Python/dark_and_darker_bard/releases/tag/ver1.4). Download script folder and run the bat file. it will worked on most song. It will worked fine in 1920X1080 resolution. But you should try it on your pc and adjust setting.txt or image.png
